server {
    listen 80;
    server_name localhost;

    # Ведемо логи (вимога з ТЗ)
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        # Перенаправляємо трафік на контейнер app (ім'я береться з docker-compose)
        proxy_pass http://app:3000;
        
        # Передаємо правильні заголовки (вимоги з ТЗ)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Дозволяємо Nginx перехоплювати помилки додатку
        proxy_intercept_errors on;
    }
}
